const SpectrumCards: [string, string][] = [
    ["rossz", "jó"],
    ["kevésbé tesz függővé", "nagyon függővé tesz"],
    ["forró", "fagyos"],
    ["normális", "furcsa"],
    ["színtelen", "színes"],
    ["alacsony kalóriatartalmú", "magas kalóriatartalmú"],
    ["rossz érzés", "jó érzés"],
    ["nélkülözhető", "nélkülözhetetlen"],
    ["olcsó", "drága"],
    ["alábecsült fegyver", "túlértékelt fegyver"],
    ["ritka", "gyakori"],
    ["visszataszító hangulatjel", "vonzó hangulatjel"],
    ["könnyű téma", "nehéz téma"],
    ["ismeretlen", "közismert"],
    ["nehezen használható", "könnyen használható"],
    ["divatjamúlt", "divatos"],
    ["piszkos", "tiszta"],
    ["szerencse kell hozzá", "szakértelem kell hozzá"],
    ["íztelen", "ízletes"],
    ["unalmas téma", "izgalmas téma"],
    ["rossz színész", "jó színész"],
    ["átlagos", "különc"],
    ["veszélyes munka", "biztonságos munka"],
    ["fantasy", "sci-fi"],
    ["hétköznapi", "alkalmi"],
    ["alulfizetett", "túlfizetett"],
    ["száraz", "nedves"],
    ["alábecsült szakértelem", "túlértékelt szakértelem"],
    ["tiltott", "bátorított"],
    ["szomorú dal", "vidám dal"],
    ["törékeny", "tartós"],
    ["kocka", "ütődött"],
    ["jó", "gonosz"],
    ["az év legrosszabb napja", "az év legjobb napja"],
    ["rossz szokás", "jó szokás"],
    ["macskabarát", "kutyabarát"],
    ["bűnös élvezet", "nyílt szerelem"],
    ["tehetségtelen", "tehetséges"],
    ["sötét", "világos"],
    ["alábecsült színész", "túlértékelt színész"],
    ["nehezen megtalálható", "könnyen megtalálható"],
    ["ronda férfi", "gyönyörű férfi"],
    ["nehezen megközelíthető", "könnyen megjegyezhető"],
    ["polgári", "sznob"],
    ["egészségtelen", "egészséges"],
    ["rossz ember", "jó ember"],
    ["történelmileg jelentős", "történelmileg jelentéktelen"],
    ["szőrtelen", "szőrös"],
    ["merev", "hajlékony"],
    ["nem egzotikus háziállat", "egzotikus háziállat"],
    ["introvertált", "extrovertált"],
    ["a könyv jobb volt", "a film jobb volt"],
    ["rossz film", "jó film"],
    ["ronda", "gyönyörű"],
    ["lassan történik", "hirtelen történik"],
    ["foglalkozás", "karrier"],
    ["imádott", "gyűlölt"],
    ["az Erő világos oldala", "az Erő sötét oldala"],
    ["rossz pizza feltét", "jó pizza feltét"],
    ["dísztópia", "utópia"],
    ["érett személyiség", "éretlen személyiség"],
    ["alábecsült dolog amit birtokolhatsz", "túlértékelt dolog amit birtokolhatsz"],
    ["barátságtalan személy", "barátságos személy"],
    ["akciófilm", "kalandfilm"],
    ["szellemi tevékenység", "fizikai tevékenység"],
    ["nem vitatott téma", "vitatott téma"],
    ["szükség", "vágy"],
    ["száraz étel", "vizes étel"],
    ["normális dolog amit birtokolhatsz", "furcsa dolog amit birtokolhatsz"],
    ["egyenes", "görbe"],
    ["80-as évek", "90-es évek"],
    ["etikus megenni", "nem etikus megenni"],
    ["nem művészfilm", "művészfilm"],
    ["választható", "kötelező"],
    ["alábecsült betűje az ábécének", "túlértékelt betűje az ábécének"],
    ["közönséges", "rendkívüli"],
    ["nehéz kiejtetni", "könnyű kiejteni"],
    ["alacsony minőségű", "magas minőségű"],
    ["visszataszító élőlény", "vonzó élőlény"],
    ["puritán", "giccses"],
    ["rossz hírnevű", "jó hírnevű"],
    ["silányul elkészített", "remekül elkészített"],
    ["nem egy szendvics", "egy szendvics"],
    ["csendes hely", "zajos hely"],
    ["komédia", "dráma"],
    ["veszélyes", "biztonságos"],
    ["kulturálisan jelentős", "kulturálisan jelentéktelen"],
    ["pótolható", "pótolhatatlan"],
    ["a valaha élt legrosszabb sportoló", "a valaha élt legjobb sportoló"],
    ["követendő példa", "nem követendő példa"],
    ["haszontalan végzettség", "hasznos végzettség"],
    ["békés", "harcias"],
    ["alábecsült film", "túlértékelt film"],
    ["egyenetlen", "sima"],
    ["rossz neked", "jó neked"],
    ["tompa", "hegyes"],
    ["bizonyíték Isten létezésére", "cáfolat Isten létezésére"],
    ["szomorú film", "vidám film"],
    ["haszontalan időtöltés", "hasznos időtöltés"],
    ["ijesztő állat", "aranyos állat"],
    ["elterjedt", "szűkebb réteget megcélzó"],
    ["rövid életű", "hosszú életű"],
    ["senki se csinálja", "mindenki csinálja"],
    ["büdös", "illatos"],
    ["nassolnivaló", "főétel"],
    ["legkevésbé gonosz cég", "leggonoszabb cég"],
    ["puha", "kemény"],
    ["kaja", "étel költemény"],
    ["szögletes", "kerek"],
    ["melegen jobb", "hidegen jobb"],
    ["hülye", "briliáns"],
    ["kézműves termék", "tömegtermék"],
    ["rossz szuperképesség", "jó szuperképesség"],
    ["hatástalan", "hatásos"],
    ["hihetetlen", "hihető"],
    ["ízléstelen", "ízléses"],
    ["ideiglenes", "állandó"],
    ["úgy néz ki mint egy ember", "nem úgy néz ki mint egy ember"],
    ["rossz ízű", "jó ízű"],
    ["sport", "játék"],
    ["nem menő", "menő"],
    ["a legrosszabb élő személy", "a legjobb élő személy"],
    ["alábecsült", "túlértékelt"],
    ["étel amit nem lehet szépen enni", "étel amit szépen lehet enni"],
    ["nem etikus", "etikus"],
    ["rossz ajándék", "jó ajándék"],
    ["szabadságharcos", "terrorista"],
    ["megbocsáthatatlan", "megbocsátható"],
    ["kudarc", "mestermű"],
    ["ártalmatlan", "ártalmas"],
    ["nem higiénikus", "higiénikus"],
    ["rossz zene", "jó zene"],
    ["haszontalan", "hasznos"],
    ["film amit Godzilla elrontana", "film amit Godzilla jobbá tenne"],
    ["jelentéktelen", "fontos"],
    ["könnyű kibetűzni", "nehéz kibetűzni"],
    ["jellemhiba", "erény"],
    ["alábecsült zenész", "túlértékelt zenész"],
    ["népszerűtlen tevékenység", "népszerű tevékenység"],
    ["szétdarabolt", "teljes"],
    ["megbízhatatlan", "megbízható"],
    ["könnyű megölni", "nehéz megölni"],
    ["instabil", "stabil"],
    ["kerek állaat", "szögletes állat"],
    ["rossz filmsorozat", "jó filmsorozat"],
    ["hagyományosan férfias", "hagyományosan nőies"],
    ["haszontalan testrész", "hasznos testrész"],
    ["trendi", "klasszikus"],
    ["gyenge", "erős"],
    ["undorító gabonapehely", "ízletes gabonapehely"],
    ["haszontalan találmány", "hasznos találmány"],
    ["liberális", "konzervatív"],
    ["népszerűtlen", "népszerű"],
    ["barát", "ellenség"],
    ["unalmas", "izgalmas"],
    ["erősen rossz szagú", "erősen jó szagú"],
    ["gazember", "hős"],
    ["alábecsült megtenni", "túlértékelt megtenni"],
    ["haszontalan egy vészhelyzetben", "hasznos egy vészhelyzetben"],
    ["gyerekeknek", "felnőtteknek"],
    ["bölcs", "intelligens"],
    ["könnyű megtenni", "nehéz megtenni"],
    ["értéktelen", "felbecsülhetetlen"],
    ["veleszületett", "nevelt"],
    ["diktatúra", "demokrácia"],
    ["szokványos üdvözlés", "szokatlan üdvözlés"],
    ["kutya név", "macska név"],
    ["nem elfogult", "elfogult"],
    ["véges", "végtelen"],
    ["hétköznapi esemény", "hivatalos esemény"],
    ["rossz befektetés", "jó befektetés"],
    ["csevej", "nehéz téma"],
    ["íztelen", "fűszeres"],
    ["vallásos", "szentségtörő"],
    ["nem művészet", "művészet"],
    ["illegális", "tiltott"],
    ["populáris", "elitista"],
    ["irányíthatatlan", "irányított"],
    ["csendes", "hangos"],
    ["titkos", "köztudott"],
    ["túl kicsi", "túl nagy"],
    ["rövid", "hosszú"],
    ["a történelem legrosszabb éve", "a történelem legjobb éve"],
    ["szocialista", "kapitalista"],
    ["kevéssé ismert tény", "jól ismert tény"],
    ["helyhez kötött", "mozgatható"],
    ["helyi probléma", "világméretű probléma"],
    ["tehetség", "szakértelem"],
    ["a legrosszabb korszak ahova időutazhatsz", "a legjobb korszak ahova időutazhatsz"],
    ["a legrosszabb", "a legjobb"],
    ["kisszámú", "nagy számú"],
    ["igaz", "hamis"],
    ["régimódi", "avantgárd"],
    ["undorító szó", "gyönyörű szó"],
    ["természetellenes", "természetes"],
    ["hiteles ember", "hiteltelen ember"],
    ["származékos", "eredeti"],
    ["etikett", "modor"],
    ["visszataszító szín", "vonzó szín"],
    ["hasznodra válik", "mindenki hasznára válik"],
    ["erőtlen", "erőteljes"],
    ["nem tölthető elektromos cigarettába", "elektromos cigarettába tölthető"],
    ["gyümölcs", "zöldség"],
    ["tudomány", "sarlatánság"],
    ["vicces téma", "komoly tétma"],
    ["bűnös élvezet", "egyszerűen csak rossz"],
    ["pletyka", "hír"],
    ["nehéz ülni rajta", "könnyű ülni rajta"],
    ["nem elég", "túl sok"],
    ["vízszintes", "függőleges"],
    ["szagtalan", "illatosított"],
    ["ölelhető", "nem ölelhető"],
    ["heterogén", "homogén"],
    ["inkluzív", "exkluzív"],
    ["rossz kutya fajta", "jó kutya fajta"],
    ["művészet", "üzlet"],
    ["egyslágeres előadó", "pop ikon"],
    ["rossz tanács", "jó tanács"],
    ["tikk", "takk"],
    ["rossz édesség", "jó édesség"],
    ["tradicionális", "radikális"],
    ["rossz szájíz", "jó szájíz"],
    ["illegális", "legális"],
    ["mély gondolat", "sekélyes gondolat"],
    ["rossz iskola", "jó iskola"],
    ["sosem időben", "mindig időben"],
    ["nem fog 100 évig élni", "100 évig fog élni"],
    ["rossz Disney szereplő", "jó Disney szereplő"],
    ["hasonló", "ugyanolyan"],
    ["rossz vezető", "jó vezető"],
    ["bizarr", "furcsa"],
    ["híres", "hírhedt"],
    ["a legjelentéktelenebb isten", "a leghatalmasabb isten"],
    ["unalmas ember", "szórakoztató ember"],
    ["alábecsült könyv", "túlértékelt könyv"],
    ["közismert tény", "alternatív tény"],
    ["legrosszabb házimunka", "legjobb házimunka"],
    ["veszélyeztetett állatfaj", "túlnépesedett állatfaj"],
    ["kék", "zöld"],
    ["izgalmas", "félelmetes"],
    ["okostojás", "macsó"],
    ["várható", "váratlan"],
    ["akit el tudnál verni", "akit nem tudnál elverni"],
    ["érthetetlen fóbia", "érthető fóbia"],
    ["alábecsült játék", "túlértékelt játék"],
];

const AdvancedSpectrumCards: [string, string][] = [
    ["Griffendél", "Mardekár"],
    ["visszataszító Pokémon", "vonzó Pokémon"],
    ["Star Wars", "Star Trek"],
    ["kicsi", "apró"],
];

export const AllCards = [...SpectrumCards, ...AdvancedSpectrumCards];
